### ISSUE TITLE
Feature Request: Upload & Posting to Profile 

### ISSUE THREAD

**Issue by possibly-a-man** [Furry/byte-api#6]
Description: The ability to upload and post to profile.

Findings: So far I've found you can post to /upload to get the cdn info.

```js
// using this as the body, headers are the standard application/json content-type and auth with token
{
    contentType: 'video/mp4',
    file: file // base64 encoded is how i sent it successfully
}

// this returns:
{
  uploadID: 'String ID redacted',
  uploadURL: 'String google cdn link redacted'
}
```

I've also found posting to /upload with only the payload being contentType: 'video/mp4' or 'image/jpeg' returns cdn stuff.

I think the actual post endpoint may be /post

This is the only helpful thing I've found so far: https://github.com/MixV2/ByteSharp/blob/master/ByteSharp/Models/ByteUpload.cs

According to this, videos must be under 5MB.

**Comment by Furry** [comment]
I'll work on this issue both tonight & tomorrow.

The current plan is to use [Fluent-FFMPEG](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) to Trim videos exceeding the max length down automatically, downloading the direct url of the post if need be.

**Comment by possibly-a-man** [comment]
update I got it working and most of what I said initially was wrong lmao but here are actually the steps simplified for future reference:

Step 1:
post to /upload
```
// may also wanna be using user agent headers
 headers: {
      'Content-Type': 'application/json',
      Authorization: '<your token>'
    }

payload: {
    contentType: 'video/mp4'
  }
```
returns data with an uploadID and uploadURL

Step 2:

put to that uploadURL

```
 headers: {
      'Content-Type': 'video/mp4'
    }

// payload is just an mp4 file, 5MB limit, seems to also have min length limit but unsure exactly.
```

Step 3: 

post to /post

```
 headers: {
      'Content-Type': 'application/json',
      Authorization: '<your token>'
    }

payload:{
    category: '<any category on byte>',
    videoUploadID :'uploadID from step 1 ,
    thumbUploadID: 'uploadID from step 1,
    caption: '<your caption>'
  }
``
that will return a video object

credit to mix and his examples which basically showed the way.

**Comment by possibly-a-man** [comment]
Was added in https://github.com/Furry/byte-api/commit/340a8a8bb02bcdc7936fa325ebe572e700bee8b2
